version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
      - echo ~/.ssh/id_rsa

  build:
    commands:
      - ./terraform init
      - ./terraform apply -auto-approve


