version: 0.2

env:
    parameter-store:
      TF_VAR_rds_default_username: "DB_username"
      TF_VAR_rds_default_password: "DB_password"           

artifacts:
  files:
    - '**/*'

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo $TF_VAR_rds_default_username
      - curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/0.12.18/terraform_0.12.18_linux_amd64.zip
      - unzip -o terraform.zip
      - ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
      - cat ~/.ssh/id_rsa

  build:
    commands:
      - ./terraform init 
      - ./terraform plan

