version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/0.12.18/terraform_0.12.18_linux_amd64.zip
      - jar xvf terraform.zip
      - chmod +x terraform
      - ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
      - echo ~/.ssh/id_rsa
      - EXPORT  aws_access_key_id=AKIAUGOOIHIFWLV4YBCO
      - EXPORT  aws_secret_access_key=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    
   
  build:
    commands:
      - ./terraform init
      - ./terraform apply -auto-approve


