version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/0.12.18/terraform_0.12.18_linux$
      - unzip -o terraform.zip
      - ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
      - echo ~/.ssh/id_rsa

  build:
    commands:
      - ./terraform init
      - ./terraform apply -auto-approve


