version: 0.2

env:
    parameter-store:
      TF_VAR_rds_default_username: "DB_username"
      TF_VAR_rds_default_password: "DB_password"

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - git --version
      - curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/0.12.18/terraform_0.12.18_linux_amd64.zip
      - jar xvf terraform.zip
      - chmod +x terraform

  build:
    commands:
      - ./terraform init
      - aws s3 cp s3://s3-codepipeline-ziqy/ ./ --recursive
      - ./terraform apply -auto-approve
      - aws s3 cp terraform.tfstate s3://s3-codepipeline-ziqy/terraform.tfstate

