version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/0.12.18/terraform_0.12.18_linux_amd64.zip"
      - "unzip -o terraform.zip"

   build:
    commands:
      - "./terraform plan"

